---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-5.11
  - name: centos-6.7
  - name: centos-7.2
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[cron]
      - recipe[cron_wom_test]
