name             'cron_wom_test'
maintainer       'Peter Walz, University of Minnesota'
maintainer_email 'pnw@umn.edu'
license          'Apache 2.0'
description      'Used only for testing the parent cookbook (cron_wom)'
version          '1.0.0'
depends          'cron_wom'
